---
# Source: stub-helm-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: stub-helm-chart
    chart: stub-helm-chart-3.3.1
    release: release-name
    heritage: Tiller
  name: svcacct1


---
# Source: stub-helm-chart/templates/lb.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stub-helm-chart
  name: external
  namespace: debug
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: website
  type: LoadBalancer

---
# Source: stub-helm-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-stub-helm-chart
  namespace: debug
  labels:
    app: stub-helm-chart
    chart: stub-helm-chart-3.3.1
    release: release-name
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websites
  template:
    metadata:
      labels:
        app: websites
    spec:
      containers:
      - name: site
        image: gcr.io/pr-com-203715/simple_website:yall
        ports:
        - containerPort: 80
          protocol: TCP

