apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websites
  template:
    metadata:
      labels:
        app: websites
    spec:
      containers:
      - name: site
        image: gcr.io/pr-com-203715/simple_website
        ports:
        - containerPort: 80
          protocol: TCP
